-- Inserimento dati nella tabella Cards
INSERT INTO ConcordiaStation.dbo.Experiments(Title)
VALUES
('Esperimento di Fusione Nucleare'),
('Esperimento di Clonazione Genetica'),
('Esperimento di Teletrasporto Molecolare'),
('Esperimento di Bioingegneria'),
('Esperimento di Criogenia'),
('Esperimento di Realtà Virtuale');


INSERT INTO ConcordiaStation.dbo.Phases (IdCardTrello, Title, dateOfCreation, lastActivity, Description, Deadline, Priority, Status, LastComment, ExperimentId)
VALUES
('card_trello', 'Calibrazione strumenti', '2023-06-10', '2023-06-10', 'Calibrare gli strumenti di misurazione', '2023-06-10', 1, 0, NULL, 1),
('card_trello', 'Preparazione attrezzatura', '2023-06-11', '2023-06-11', 'Preparare l''attrezzatura per il prelievo', '2023-06-11', 2, 1, NULL, 1),
('card_trello', 'Prelievo campioni aria', '2023-06-12', '2023-06-12', 'Prelevare campioni di aria', '2023-06-12', 3, 2, NULL, 1),
('card_trello', 'Analisi composizione campioni', '2023-06-13', '2023-06-13', 'Analizzare la composizione dei campioni raccolti', '2023-06-13', 1, 1, NULL, 1),
('card_trello', 'Valutazione inquinanti', '2023-06-14', '2023-06-14', 'Valutare la presenza di inquinanti nei campioni', '2023-06-14', 2, 0, NULL, 2),
('card_trello', 'Preparazione substrato', '2023-06-12', '2023-06-12', 'Preparare il substrato per la coltura delle cellule', '2023-06-12', 1, 0, NULL, 2),
('card_trello', 'Coltivazione cellule', '2023-06-13', '2023-06-13', 'Coltivare le cellule in provetta utilizzando il mezzo di coltura appropriato.', '2023-06-13', 2, 1, NULL, 2),
('card_trello', 'Preparazione reagenti', '2023-06-12', '2023-06-12', 'Preparare i reagenti necessari per l''esperimento', '2023-06-12', 1, 0, NULL, 3),
('card_trello', 'Esecuzione esperimento', '2023-06-13', '2023-06-13', 'Eseguire l''esperimento utilizzando le condizioni specificate nel protocollo', '2023-06-13', 2, 1, NULL, 3),
('card_trello', 'Analisi dati', '2023-06-14', '2023-06-14', 'Analizzare i dati ottenuti durante l''esperimento', '2023-06-14', 3, 0, NULL, 3),
('card_trello', 'Preparazione campioni', '2023-06-11', '2023-06-11', 'Preparare i campioni da utilizzare nell''esperimento', '2023-06-11', 1, 0, NULL, 4),
('card_trello', 'Trattamento campioni', '2023-06-12', '2023-06-12', 'Trattare i campioni con il trattamento sperimentale', '2023-06-12', 2, 1, NULL, 4),
('card_trello', 'Analisi risultati', '2023-06-13', '2023-06-13', 'Analizzare i risultati dell''esperimento', '2023-06-13', 3, 0, NULL, 4),
('card_trello', 'Preparazione campione', '2023-06-12', '2023-06-12', 'Preparare il campione da sottoporre a criogenia', '2023-06-12', 1, 0, NULL, 5),
('card_trello', 'Crioconservazione', '2023-06-13', '2023-06-13', 'Sottoporre il campione a criogenia utilizzando un metodo appropriato', '2023-06-13', 2, 1, NULL, 5),
('card_trello', 'Controllo qualità', '2023-06-14', '2023-06-14', 'Effettuare controlli di qualità sul campione criopreservato', '2023-06-14', 3, 0, NULL, 5),
('card_trello', 'Configurazione ambiente virtuale', '2023-06-13', '2023-06-13', 'Configurare l''ambiente virtuale per l''esperimento di realtà virtuale', '2023-06-13', 1, 0, NULL, 6),
('card_trello', 'Esecuzione esperimento', '2023-06-14', '2023-06-14', 'Eseguire l''esperimento utilizzando l''ambiente virtuale', '2023-06-14', 2, 1, NULL, 6),
('card_trello', 'Valutazione risultati', '2023-06-15', '2023-06-15', 'Valutare i risultati ottenuti durante l''esperimento di realtà virtuale', '2023-06-15', 3, 0, NULL, 6);

-- Inserimento dati nella tabella Scientists
INSERT INTO ConcordiaStation.dbo.Scientists (GivenName, FamilyName, PhaseId)
VALUES
('John', 'Doe', 1),
('Jane', 'Smith', 2),
('Robert', 'Johnson', 3),
('Michael', 'Brown', 4),
('Emily', 'Davis', 5),
('Daniel', 'Wilson', 6),
('Sophia', 'Taylor', 7),
('David', 'Anderson', 8),
('Olivia', 'Miller', 9),
('William', 'Clark', 10),
('Emma', 'Walker', 11),
('James', 'Harris', 12),
('Ava', 'Lewis', 13),
('Benjamin', 'Hall', 14),
('Mia', 'Robinson', 15),
('Alexander', 'Young', 16),
('Charlotte', 'Lee', 17),
('Daniel', 'Allen', 18),
('Grace', 'Wright', 19),
('Samuel', 'Martin', 1),
('Ella', 'Hall', 2),
('Joseph', 'Baker', 3),
('Scarlett', 'Garcia', 4),
('Matthew', 'Perez', 5),
('Victoria', 'Smith', 6),
('Henry', 'Jackson', 7),
('Lily', 'Davis', 8),
('Anthony', 'White', 9),
('Abigail', 'Thomas', 10),
('Christopher', 'Anderson', 11),
('Sofia', 'Williams', 12),
('Andrew', 'Taylor', 13),
('Grace', 'Martin', 14),
('Jacob', 'Lee', 15),
('Sophia', 'Gonzalez', 16),
('Logan', 'Rodriguez', 17),
('Isabella', 'Walker', 18),
('Ethan', 'Moore', 19),
('Mia', 'Gonzalez', 1),
('Matthew', 'Garcia', 2),
('Olivia', 'Thomas', 3),
('Jayden', 'Anderson', 4),
('Amelia', 'Clark', 5),
('Lucas', 'Young', 6),
('Elizabeth', 'Davis', 7),
('Michael', 'Williams', 8),
('Evelyn', 'Brown', 9),
('Daniel', 'Wilson', 10),
('Madison', 'Smith', 11),
('Aiden', 'Johnson', 12),
('Emily', 'Robinson', 13),
('Jacob', 'Wilson', 14),
('Sophia', 'Hall', 15),
('Alexander', 'White', 16),
('Abigail', 'Jackson', 17),
('Benjamin', 'Brown', 18),
('Ava', 'Miller', 19),
('Matthew', 'Davis', 1),
('Charlotte', 'Moore', 2),
('Samuel', 'Lewis', 3),
('Scarlett', 'Thomas', 4),
('David', 'Taylor', 5),
('Grace', 'Wilson', 6),
('Ethan', 'Anderson', 7),
('Lily', 'Garcia', 8),
('Henry', 'Smith', 9),
('Elizabeth', 'Hall', 10),
('Christopher', 'Martin', 11),
('Sofia', 'Walker', 12),
('Daniel', 'Young', 13),
('Amelia', 'Allen', 14),
('James', 'Jones', 15),
('Avery', 'Clark', 16),
('Emily', 'Rod', 17),
('SHINOBI', 'SENZA NOME', 18); 



INSERT INTO ConcordiaStation.dbo.Comments (Content, CommentTime, PhaseId, ScientistId)
VALUES
('Ottimo lavoro sul nuovo algoritmo di analisi dati!', DATEADD(day, -3, GETDATE()), 1, 1),
('Stiamo facendo progressi significativi nella sintesi del composto X!', DATEADD(day, -2, GETDATE()), 1, 20),
('I risultati preliminari dell''esperimento Y sono molto promettenti.', DATEADD(day, -1, GETDATE()), 1, 39),
('Continuate così, il vostro contributo è fondamentale per il progetto.', GETDATE(), 1, 58),
('Abbiamo riscontrato alcune sfide nella fase di test del prototipo.', DATEADD(day, -4, GETDATE()), 1, 1),
('I dati raccolti oggi forniscono nuove intuizioni sul fenomeno Z.', DATEADD(day, -3, GETDATE()), 1, 20),
('Il team ha dimostrato grande collaborazione nel superare gli ostacoli tecnici.', DATEADD(day, -1, GETDATE()), 1, 39),
('Oggi abbiamo raggiunto un nuovo record di efficienza!', GETDATE(), 1, 58),
('I risultati dell''esperimento W sono stati pubblicati su una rivista di prestigio.', DATEADD(day, -2, GETDATE()), 1, 1),
('Complimenti a tutti per l''ottimo lavoro di squadra!', DATEADD(day, -3, GETDATE()), 1, 20),
('Le nuove attrezzature acquisite hanno migliorato notevolmente la nostra capacità di ricerca.', DATEADD(day, -1, GETDATE()), 1, 39),
('Grazie a tutti per il vostro impegno costante nello studio del fenomeno Y.', GETDATE(), 1, 58),
('Grande lavoro nell''analisi dei dati del progetto!', DATEADD(day, -3, GETDATE()), 2, 2),
('Stiamo facendo notevoli progressi nello sviluppo del composto Y!', DATEADD(day, -2, GETDATE()), 2, 21),
('I risultati dell''esperimento Z sono molto promettenti.', DATEADD(day, -1, GETDATE()), 2, 40),
('Il tuo contributo è essenziale per il successo del progetto. Continua così!', GETDATE(), 2, 59),
('Abbiamo incontrato alcune sfide durante i test del prototipo. Rimani concentrato!', DATEADD(day, -4, GETDATE()), 2, 2),
('I dati raccolti oggi forniscono nuove prospettive sul fenomeno X.', DATEADD(day, -3, GETDATE()), 2, 21),
('Il team ha dimostrato grande collaborazione nel superare gli ostacoli tecnici.', DATEADD(day, -1, GETDATE()), 2, 40),
('Oggi abbiamo raggiunto un nuovo record di efficienza nel laboratorio!', GETDATE(), 2, 59),
('I risultati dell''esperimento W sono stati pubblicati su una rinomata rivista scientifica.', DATEADD(day, -2, GETDATE()), 2, 2),
('Complimenti a tutti per il fantastico lavoro svolto insieme!', DATEADD(day, -3, GETDATE()), 2, 21),
('Le nuove attrezzature acquisite hanno potenziato le nostre capacità di ricerca.', DATEADD(day, -1, GETDATE()), 2, 40),
('Grazie a te e a tutto il team per l''impegno costante nella ricerca di nuove soluzioni.', GETDATE(), 2, 59),
('Ottimo lavoro nella fase di sviluppo avanzato!', DATEADD(day, -3, GETDATE()), 3, 3),
('Continuiamo a fare progressi significativi nella ricerca del composto Z!', DATEADD(day, -2, GETDATE()), 3, 22),
('I risultati dell''esperimento X sono molto interessanti.', DATEADD(day, -1, GETDATE()), 3, 41),
('Il tuo contributo è fondamentale per il successo della fase sperimentale. Grazie!', GETDATE(), 3, 60),
('Abbiamo superato con successo le sfide nella fase di test del nuovo dispositivo.', DATEADD(day, -4, GETDATE()), 3, 3),
('I dati raccolti oggi forniscono nuove intuizioni sul fenomeno Y.', DATEADD(day, -3, GETDATE()), 3, 22),
('Il team ha dimostrato una grande collaborazione nel raggiungimento degli obiettivi.', DATEADD(day, -1, GETDATE()), 3, 41),
('Oggi abbiamo raggiunto un importante traguardo nella ricerca!', GETDATE(), 3, 60),
('I risultati dell''esperimento W sono stati presentati con successo alla conferenza internazionale.', DATEADD(day, -2, GETDATE()), 3, 3),
('Complimenti a tutti per l''eccellente lavoro svolto!', DATEADD(day, -3, GETDATE()), 3, 22),
('Le nuove attrezzature acquisite hanno migliorato notevolmente la nostra produttività di laboratorio.', DATEADD(day, -1, GETDATE()), 3, 41),
('Grazie a te e a tutto il team per l''impegno costante nella fase di ricerca avanzata.', GETDATE(), 3, 60),
('Il progetto nella fase di valutazione è in buon andamento!', DATEADD(day, -3, GETDATE()), 4, 4),
('Stiamo ottenendo risultati promettenti nello studio del composto A!', DATEADD(day, -2, GETDATE()), 4, 23),
('I dati preliminari dell''esperimento B sono molto interessanti.', DATEADD(day, -1, GETDATE()), 4, 42),
('Il tuo contributo è fondamentale per il successo della fase di valutazione. Grazie per l''impegno!', GETDATE(), 4, 61),
('Abbiamo superato con successo le sfide nella fase di test del nuovo prototipo.', DATEADD(day, -4, GETDATE()), 4, 4),
('I dati raccolti oggi forniscono ulteriori intuizioni sul fenomeno C.', DATEADD(day, -3, GETDATE()), 4, 23),
('Il team ha dimostrato una grande collaborazione nel raggiungimento degli obiettivi.', DATEADD(day, -1, GETDATE()), 4, 42),
('Oggi abbiamo raggiunto un importante traguardo nella fase di valutazione!', GETDATE(), 4, 61),
('I risultati dell''esperimento D sono stati condivisi con successo con i colleghi.', DATEADD(day, -2, GETDATE()), 4, 4),
('Complimenti a tutti per l''eccellente lavoro svolto nella fase di valutazione!', DATEADD(day, -3, GETDATE()), 4, 23),
('Le nuove attrezzature acquisite hanno migliorato notevolmente la nostra produttività di laboratorio.', DATEADD(day, -1, GETDATE()), 4, 42),
('Grazie a te e a tutto il team per l''impegno costante nella fase di valutazione del progetto.', GETDATE(), 4, 61),
('Stiamo facendo grandi progressi nella fase di ottimizzazione!', DATEADD(day, -3, GETDATE()), 5, 5),
('Continuiamo a ottenere risultati significativi nello studio del composto D!', DATEADD(day, -2, GETDATE()), 5, 23),
('I dati preliminari dell''esperimento E sono molto promettenti.', DATEADD(day, -1, GETDATE()), 5, 43),
('Il tuo contributo è fondamentale per il successo della fase di ottimizzazione. Grazie per il tuo impegno!', GETDATE(), 5, 62),
('Abbiamo superato con successo le sfide nella fase di test del nuovo processo.', DATEADD(day, -4, GETDATE()), 5, 5),
('I dati raccolti oggi forniscono nuove prospettive sul fenomeno F.', DATEADD(day, -3, GETDATE()), 5, 24),
('Il team ha dimostrato grande collaborazione nel raggiungimento degli obiettivi.', DATEADD(day, -1, GETDATE()), 5, 43),
('Oggi abbiamo raggiunto un importante traguardo nella fase di ottimizzazione!', GETDATE(), 5, 62),
('I risultati dell''esperimento G sono stati condivisi con successo con i partner.', DATEADD(day, -2, GETDATE()), 5, 5),
('Complimenti a tutti per l''eccellente lavoro svolto nella fase di ottimizzazione!', DATEADD(day, -3, GETDATE()), 5, 24),
('Le nuove attrezzature acquisite hanno migliorato notevolmente la nostra produttività di laboratorio.', DATEADD(day, -1, GETDATE()), 5, 43),
('Grazie a te e a tutto il team per l''impegno costante nella fase di ottimizzazione del progetto.', GETDATE(), 5, 62),
('Il progetto nella fase di ottimizzazione avanzata sta procedendo alla grande!', DATEADD(day, -3, GETDATE()), 6, 6),
('Stiamo ottenendo risultati eccezionali nello studio del composto G!', DATEADD(day, -2, GETDATE()), 6, 25),
('I dati preliminari dell''esperimento H sono molto promettenti.', DATEADD(day, -1, GETDATE()), 6, 44),
('Il tuo contributo è fondamentale per il successo della fase di ottimizzazione avanzata. Grazie per l''impegno!', GETDATE(), 6, 63),
('Abbiamo superato con successo le sfide nella fase di test del nuovo approccio.', DATEADD(day, -4, GETDATE()), 6, 6),
('I dati raccolti oggi forniscono nuove prospettive sul fenomeno I.', DATEADD(day, -3, GETDATE()), 6, 25),
('Il team ha dimostrato una grande collaborazione nel raggiungimento degli obiettivi.', DATEADD(day, -1, GETDATE()), 6, 44),
('Oggi abbiamo raggiunto un importante traguardo nella fase di ottimizzazione avanzata!', GETDATE(), 6, 63),
('I risultati dell''esperimento J sono stati condivisi con successo con i collaboratori.', DATEADD(day, -2, GETDATE()), 6, 6),
('Complimenti a tutti per l''eccellente lavoro svolto nella fase di ottimizzazione avanzata!', DATEADD(day, -3, GETDATE()), 6, 25),
('Le nuove attrezzature acquisite hanno migliorato notevolmente la nostra produttività di laboratorio.', DATEADD(day, -1, GETDATE()), 6, 44),
('Grazie a te e a tutto il team per l''impegno costante nella fase di ottimizzazione avanzata del progetto.', GETDATE(), 6, 63),
('Il progetto nella fase finale sta raggiungendo risultati straordinari!', DATEADD(day, -3, GETDATE()), 7, 7),
('Stiamo facendo progressi significativi nello studio del composto J!', DATEADD(day, -2, GETDATE()), 7, 26),
('I risultati preliminari dell''esperimento K sono molto promettenti.', DATEADD(day, -1, GETDATE()), 7, 45),
('Il tuo contributo è fondamentale per il successo della fase finale. Grazie per l''impegno!', GETDATE(), 7, 64),
('Abbiamo superato con successo le sfide nella fase di test del nuovo sistema.', DATEADD(day, -4, GETDATE()), 7, 7),
('I dati raccolti oggi forniscono ulteriori intuizioni sul fenomeno L.', DATEADD(day, -3, GETDATE()), 7, 26),
('Il team ha dimostrato una grande collaborazione nel raggiungimento degli obiettivi.', DATEADD(day, -1, GETDATE()), 7, 45),
('Oggi abbiamo raggiunto un importante traguardo nella fase finale!', GETDATE(), 7, 64),
('I risultati dell''esperimento M sono stati condivisi con successo con i partner di ricerca.', DATEADD(day, -2, GETDATE()), 7, 7),
('Complimenti a tutti per l''eccellente lavoro svolto nella fase finale del progetto!', DATEADD(day, -3, GETDATE()), 7, 26),
('Le nuove attrezzature acquisite hanno migliorato notevolmente la nostra produttività di laboratorio.', DATEADD(day, -1, GETDATE()), 7, 45),
('Grazie a te e a tutto il team per l''impegno costante nella fase finale del progetto.', GETDATE(), 7, 64),
('I risultati ottenuti nella fase finale superano ogni aspettativa!', DATEADD(day, -3, GETDATE()), 8, 8),
('Stiamo compiendo grandi progressi nello studio del composto M!', DATEADD(day, -2, GETDATE()), 8, 27),
('I risultati preliminari dell''esperimento N sono estremamente promettenti.', DATEADD(day, -1, GETDATE()), 8, 46),
('Il tuo contributo è fondamentale per il successo della fase finale. Grazie per l''impegno!', GETDATE(), 8, 65),
('Abbiamo superato con successo le sfide nella fase di test del nuovo dispositivo.', DATEADD(day, -4, GETDATE()), 8, 8),
('I dati raccolti oggi offrono nuove prospettive sul fenomeno O.', DATEADD(day, -3, GETDATE()), 8, 27),
('Il team ha dimostrato una straordinaria collaborazione nel raggiungimento degli obiettivi.', DATEADD(day, -1, GETDATE()), 8, 46),
('Oggi abbiamo raggiunto un traguardo eccezionale nella fase finale!', GETDATE(), 8, 65),
('I risultati dell''esperimento P sono stati condivisi con successo con i collaboratori.', DATEADD(day, -2, GETDATE()), 8, 8),
('Complimenti a tutti per l''eccellente lavoro svolto nella fase finale del progetto!', DATEADD(day, -3, GETDATE()), 8, 27),
('Le nuove attrezzature acquisite hanno notevolmente migliorato la nostra produttività di laboratorio.', DATEADD(day, -1, GETDATE()), 8, 46),
('Grazie a te e a tutto il team per l''impegno costante nella fase finale del progetto.', GETDATE(), 8, 65),
('I risultati ottenuti nella fase avanzata sono eccezionali!', DATEADD(day, -3, GETDATE()), 9, 9),
('Stiamo facendo notevoli progressi nello studio del composto P!', DATEADD(day, -2, GETDATE()), 9, 28),
('I risultati preliminari dell''esperimento Q sono molto promettenti.', DATEADD(day, -1, GETDATE()), 9, 47),
('Il tuo contributo è fondamentale per il successo della fase avanzata. Grazie per l''impegno!', GETDATE(), 9, 66),
('Abbiamo superato con successo le sfide nella fase di test del nuovo metodo di analisi.', DATEADD(day, -4, GETDATE()), 9, 9),
('I dati raccolti oggi forniscono ulteriori intuizioni sul fenomeno R.', DATEADD(day, -3, GETDATE()), 9, 28),
('Il team ha dimostrato una grande sinergia nel raggiungimento degli obiettivi.', DATEADD(day, -1, GETDATE()), 9, 47),
('Oggi abbiamo raggiunto un importante traguardo nella fase avanzata!', GETDATE(), 9, 66),
('I risultati dell''esperimento S sono stati condivisi con successo con i collaboratori.', DATEADD(day, -2, GETDATE()), 9, 9),
('Complimenti a tutti per l''eccellente lavoro svolto nella fase avanzata del progetto!', DATEADD(day, -3, GETDATE()), 9, 28),
('Le nuove attrezzature acquisite hanno migliorato significativamente la nostra capacità di ricerca.', DATEADD(day, -1, GETDATE()), 9, 47),
('Grazie a te e a tutto il team per l''impegno costante nella fase avanzata del progetto.', GETDATE(), 9, 66),
('I risultati ottenuti nella fase avanzata sono sorprendenti!', DATEADD(day, -3, GETDATE()), 10, 10),
('Stiamo facendo progressi significativi nello studio del composto Q!', DATEADD(day, -2, GETDATE()), 10, 29),
('I risultati preliminari dell''esperimento R sono estremamente promettenti.', DATEADD(day, -1, GETDATE()), 10, 48),
('Il tuo contributo è fondamentale per il successo della fase avanzata. Grazie per l''impegno!', GETDATE(), 10, 67),
('Abbiamo superato con successo le sfide nella fase di test del nuovo dispositivo di misurazione.', DATEADD(day, -4, GETDATE()), 10, 10),
('I dati raccolti oggi offrono nuove prospettive sul fenomeno S.', DATEADD(day, -3, GETDATE()), 10, 29),
('Il team ha dimostrato una straordinaria sinergia nel raggiungimento degli obiettivi.', DATEADD(day, -1, GETDATE()), 10, 48),
('Oggi abbiamo raggiunto un traguardo eccezionale nella fase avanzata!', GETDATE(), 10, 67),
('I risultati dell''esperimento T sono stati condivisi con successo con i collaboratori.', DATEADD(day, -2, GETDATE()), 10, 10),
('Complimenti a tutti per l''eccellente lavoro svolto nella fase avanzata del progetto!', DATEADD(day, -3, GETDATE()), 10, 29),
('Le nuove attrezzature acquisite hanno notevolmente migliorato la nostra capacità di ricerca.', DATEADD(day, -1, GETDATE()), 10, 48),
('Grazie a te e a tutto il team per l''impegno costante nella fase avanzata del progetto.', GETDATE(), 10, 67),
('I risultati ottenuti nella fase finale superano ogni aspettativa!', DATEADD(day, -3, GETDATE()), 11, 11),
('Stiamo compiendo grandi progressi nello studio del composto T!', DATEADD(day, -2, GETDATE()), 11, 30),
('I risultati preliminari dell''esperimento U sono molto promettenti.', DATEADD(day, -1, GETDATE()), 11, 49),
('Il tuo contributo è fondamentale per il successo della fase finale. Grazie per l''impegno!', GETDATE(), 11, 68),
('Abbiamo superato con successo le sfide nella fase di test del nuovo metodo di analisi.', DATEADD(day, -4, GETDATE()), 11, 11),
('I dati raccolti oggi forniscono nuove intuizioni sul fenomeno V.', DATEADD(day, -3, GETDATE()), 11, 30),
('Il team ha dimostrato una grande collaborazione nel raggiungimento degli obiettivi.', DATEADD(day, -1, GETDATE()), 11, 49),
('Oggi abbiamo raggiunto un traguardo eccezionale nella fase finale!', GETDATE(), 11, 68),
('I risultati dell''esperimento W sono stati condivisi con successo con i collaboratori.', DATEADD(day, -2, GETDATE()), 11, 11),
('Complimenti a tutti per l''eccellente lavoro svolto nella fase finale del progetto!', DATEADD(day, -3, GETDATE()), 11, 30),
('Le nuove attrezzature acquisite hanno migliorato notevolmente la nostra capacità di ricerca.', DATEADD(day, -1, GETDATE()), 11, 49),
('Grazie a te e a tutto il team per l''impegno costante nella fase finale del progetto.', GETDATE(), 11, 68),
('I risultati ottenuti nella fase di analisi sono sorprendenti!', DATEADD(day, -3, GETDATE()), 12, 12),
('Stiamo facendo progressi significativi nello studio del fenomeno U!', DATEADD(day, -2, GETDATE()), 12, 31),
('I risultati preliminari dell''esperimento V sono estremamente promettenti.', DATEADD(day, -1, GETDATE()), 12, 50),
('Il tuo contributo è fondamentale per il successo della fase di analisi. Grazie per l''impegno!', GETDATE(), 12, 69),
('Abbiamo superato con successo le sfide nella fase di elaborazione dei dati.', DATEADD(day, -4, GETDATE()), 12, 12),
('I dati raccolti oggi offrono nuove prospettive sul fenomeno W.', DATEADD(day, -3, GETDATE()), 12, 31),
('Il team ha dimostrato una straordinaria sinergia nella fase di analisi.', DATEADD(day, -1, GETDATE()), 12, 50),
('Oggi abbiamo raggiunto un traguardo eccezionale nella fase di analisi!', GETDATE(), 12, 69),
('I risultati dell''esperimento X sono stati condivisi con successo con i collaboratori.', DATEADD(day, -2, GETDATE()), 12, 12),
('Complimenti a tutti per l''eccellente lavoro svolto nella fase di analisi del progetto!', DATEADD(day, -3, GETDATE()), 12, 31),
('Le nuove metodologie di analisi adottate hanno migliorato notevolmente la nostra comprensione.', DATEADD(day, -1, GETDATE()), 12, 50),
('Grazie a te e a tutto il team per l''impegno costante nella fase di analisi del progetto.', GETDATE(), 12, 69),
('I risultati ottenuti nella fase di validazione sono eccezionali!', DATEADD(day, -3, GETDATE()), 13, 13),
('Stiamo facendo notevoli progressi nello studio del fenomeno X!', DATEADD(day, -2, GETDATE()), 13, 32),
('I risultati preliminari dell''esperimento Y sono estremamente promettenti.', DATEADD(day, -1, GETDATE()), 13, 51),
('Il tuo contributo è fondamentale per il successo della fase di validazione. Grazie per l''impegno!', GETDATE(), 13, 70),
('Abbiamo superato con successo le sfide nella fase di test delle nuove tecnologie.', DATEADD(day, -4, GETDATE()), 13, 13),
('I dati raccolti oggi ci forniscono una prospettiva innovativa sul fenomeno Z.', DATEADD(day, -3, GETDATE()), 13, 32),
('Il team ha dimostrato una straordinaria collaborazione nella fase di validazione.', DATEADD(day, -1, GETDATE()), 13, 51),
('Oggi abbiamo raggiunto un risultato eccezionale nella fase di validazione!', GETDATE(), 13, 70),
('I risultati dell''esperimento W sono stati condivisi con successo con i collaboratori.', DATEADD(day, -2, GETDATE()), 13, 13),
('Complimenti a tutti per l''eccellente lavoro svolto nella fase di validazione del progetto!', DATEADD(day, -3, GETDATE()), 13, 32),
('Le nuove metodologie di validazione adottate hanno migliorato notevolmente la nostra comprensione.', DATEADD(day, -1, GETDATE()), 13, 51),
('Grazie a te e a tutto il team per l''impegno costante nella fase di validazione del progetto.', GETDATE(), 13, 70),
('I risultati ottenuti nella fase di ottimizzazione sono straordinari!', DATEADD(day, -3, GETDATE()), 14, 14),
('Stiamo facendo notevoli progressi nella ricerca del fenomeno A!', DATEADD(day, -2, GETDATE()), 14, 33),
('I risultati preliminari dell''esperimento B sono estremamente interessanti.', DATEADD(day, -1, GETDATE()), 14, 52),
('Il tuo contributo è fondamentale per il successo della fase di ottimizzazione. Grazie per l''impegno!', GETDATE(), 14, 71),
('Abbiamo superato con successo le sfide nella fase di implementazione delle nuove tecnologie.', DATEADD(day, -4, GETDATE()), 14, 14),
('I dati raccolti oggi ci offrono una nuova prospettiva sul fenomeno C.', DATEADD(day, -3, GETDATE()), 14, 33),
('Il team ha dimostrato una collaborazione eccezionale nella fase di ottimizzazione.', DATEADD(day, -1, GETDATE()), 14, 52),
('Oggi abbiamo raggiunto un risultato straordinario nella fase di ottimizzazione!', GETDATE(), 14, 71),
('I risultati dell''esperimento D sono stati condivisi con successo con i collaboratori.', DATEADD(day, -2, GETDATE()), 14, 14),
('Complimenti a tutti per l''eccellente lavoro svolto nella fase di ottimizzazione del progetto!', DATEADD(day, -3, GETDATE()), 14, 33),
('Le nuove metodologie di ottimizzazione adottate hanno portato a un significativo miglioramento.', DATEADD(day, -1, GETDATE()), 14, 52),
('Grazie a te e a tutto il team per l''impegno costante nella fase di ottimizzazione del progetto.', GETDATE(), 14, 71),
('Abbiamo ottenuto risultati eccezionali nella fase di ottimizzazione dei processi!', DATEADD(day, -3, GETDATE()), 15, 15),
('Stiamo facendo progressi significativi nello studio del fenomeno E!', DATEADD(day, -2, GETDATE()), 15, 34),
('I risultati preliminari dell''esperimento F sono molto promettenti.', DATEADD(day, -1, GETDATE()), 15, 53),
('Il tuo contributo è fondamentale per il successo della fase di ottimizzazione. Grazie per l''impegno!', GETDATE(), 15, 72),
('Abbiamo superato con successo le sfide nella fase di implementazione dei nuovi processi.', DATEADD(day, -4, GETDATE()), 15, 15),
('I dati raccolti oggi forniscono nuove intuizioni sul fenomeno G.', DATEADD(day, -3, GETDATE()), 15, 34),
('Il team ha dimostrato grande collaborazione nel superare gli ostacoli nella fase di ottimizzazione.', DATEADD(day, -1, GETDATE()), 15, 53),
('Oggi abbiamo raggiunto un nuovo record di efficienza nella fase di ottimizzazione!', GETDATE(), 15, 72),
('I risultati dell''esperimento H sono stati condivisi con successo con i collaboratori.', DATEADD(day, -2, GETDATE()), 15, 15),
('Complimenti a tutti per l''ottimo lavoro di squadra nella fase di ottimizzazione!', DATEADD(day, -3, GETDATE()), 15, 34),
('Le nuove metodologie adottate hanno migliorato notevolmente la nostra capacità di ottimizzazione.', DATEADD(day, -1, GETDATE()), 15, 53),
('Grazie a tutti per il vostro impegno costante nella fase di ottimizzazione dei processi.', GETDATE(), 15, 72),
('Siamo entusiasti dei progressi raggiunti nella fase di sperimentazione!', DATEADD(day, -3, GETDATE()), 16, 16),
('Stiamo facendo importanti scoperte nel campo della ricerca del fenomeno I!', DATEADD(day, -2, GETDATE()), 16, 35),
('I risultati preliminari dell''esperimento J sono sorprendenti e promettenti.', DATEADD(day, -1, GETDATE()), 16, 54),
('Il tuo contributo è fondamentale per il successo della fase di sperimentazione. Grazie per l''impegno!', GETDATE(), 16, 73),
('Abbiamo superato con successo le sfide nella fase di implementazione delle nuove tecnologie.', DATEADD(day, -4, GETDATE()), 16, 16),
('I dati raccolti oggi ci offrono nuove prospettive sul fenomeno K.', DATEADD(day, -3, GETDATE()), 16, 35),
('Il team ha dimostrato una grande collaborazione nel superare gli ostacoli nella fase di sperimentazione.', DATEADD(day, -1, GETDATE()), 16, 54),
('Oggi abbiamo raggiunto un risultato eccezionale nella fase di sperimentazione!', GETDATE(), 16, 73),
('I risultati dell''esperimento L sono stati condivisi con successo con i collaboratori.', DATEADD(day, -2, GETDATE()), 16, 16),
('Complimenti a tutti per l''eccellente lavoro svolto nella fase di sperimentazione!', DATEADD(day, -3, GETDATE()), 16, 35),
('Le nuove metodologie adottate hanno portato a significativi miglioramenti nella fase di sperimentazione.', DATEADD(day, -1, GETDATE()), 16, 54),
('Grazie a te e a tutto il team per l''impegno costante nella fase di sperimentazione.', GETDATE(), 16, 73),
('Siamo entusiasti dei risultati ottenuti nella fase di analisi dei dati!', DATEADD(day, -3, GETDATE()), 17, 17),
('Stiamo facendo progressi significativi nella comprensione del fenomeno M!', DATEADD(day, -2, GETDATE()), 17, 36),
('I risultati preliminari dell''esperimento N sono molto promettenti.', DATEADD(day, -1, GETDATE()), 17, 55),
('Il tuo contributo è fondamentale per il successo della fase di analisi dei dati. Grazie per l''impegno!', GETDATE(), 17, 74),
('Abbiamo superato con successo le sfide nella fase di elaborazione dei risultati.', DATEADD(day, -4, GETDATE()), 17, 17),
('I dati raccolti oggi ci forniscono nuove prospettive sul fenomeno O.', DATEADD(day, -3, GETDATE()), 17, 36),
('Il team ha dimostrato grande collaborazione nel superare gli ostacoli nella fase di analisi dei dati.', DATEADD(day, -1, GETDATE()), 17, 55),
('Oggi abbiamo ottenuto risultati eccezionali nella fase di analisi dei dati!', GETDATE(), 17, 74),
('I risultati dell''esperimento P sono stati condivisi con successo con i collaboratori.', DATEADD(day, -2, GETDATE()), 17, 17),
('Complimenti a tutti per l''ottimo lavoro di squadra nella fase di analisi dei dati!', DATEADD(day, -3, GETDATE()), 17, 36),
('Le nuove metodologie adottate hanno migliorato notevolmente la nostra capacità di analisi dei dati.', DATEADD(day, -1, GETDATE()), 17, 55),
('Grazie a tutti per il vostro impegno costante nella fase di analisi dei dati.', GETDATE(), 17, 74),
('I risultati ottenuti nella fase di ottimizzazione sono sorprendenti!', DATEADD(day, -3, GETDATE()), 18, 18),
('Stiamo facendo importanti progressi nella ricerca sul fenomeno Q!', DATEADD(day, -2, GETDATE()), 18, 37),
('I risultati preliminari dell''esperimento R sono molto promettenti.', DATEADD(day, -1, GETDATE()), 18, 56),
('Il tuo contributo è fondamentale per il successo della fase di ottimizzazione. Grazie per l''impegno!', GETDATE(), 18, 56),
('Abbiamo superato con successo le sfide nella fase di implementazione delle nuove strategie.', DATEADD(day, -4, GETDATE()), 18, 18),
('I dati raccolti oggi ci offrono nuove prospettive sul fenomeno S.', DATEADD(day, -3, GETDATE()), 18, 37),
('Il team ha dimostrato una grande collaborazione nel superare gli ostacoli nella fase di ottimizzazione.', DATEADD(day, -1, GETDATE()), 18, 56),
('Oggi abbiamo raggiunto un risultato eccezionale nella fase di ottimizzazione!', GETDATE(), 18, 56),
('I risultati dell''esperimento T sono stati condivisi con successo con i collaboratori.', DATEADD(day, -2, GETDATE()), 18, 18),
('Complimenti a tutti per l''eccellente lavoro svolto nella fase di ottimizzazione!', DATEADD(day, -3, GETDATE()), 18, 37),
('Le nuove metodologie adottate hanno portato a significativi miglioramenti nella fase di ottimizzazione.', DATEADD(day, -1, GETDATE()), 18, 56),
('Grazie a te e a tutto il team per l''impegno costante nella fase di ottimizzazione.', GETDATE(), 18, 37),
('Abbiamo raggiunto un importante traguardo nella fase di sperimentazione.', DATEADD(day, -3, GETDATE()), 19, 19),
('Stiamo facendo notevoli progressi nello studio del fenomeno U!', DATEADD(day, -2, GETDATE()), 19, 38),
('I risultati preliminari dell''esperimento V sono molto promettenti.', DATEADD(day, -1, GETDATE()), 19, 57),
('Il tuo contributo è fondamentale per il successo della fase di sperimentazione. Grazie per l''impegno!', GETDATE(), 19, 19),
('Abbiamo superato con successo le sfide nella fase di validazione dei dati.', DATEADD(day, -4, GETDATE()), 19, 38),
('I dati raccolti oggi ci offrono nuove prospettive sul fenomeno W.', DATEADD(day, -3, GETDATE()), 19, 57),
('Il team ha dimostrato una grande collaborazione nel superare gli ostacoli nella fase di sperimentazione.', DATEADD(day, -1, GETDATE()), 19, 19),
('Oggi abbiamo raggiunto un risultato eccezionale nella fase di sperimentazione!', GETDATE(), 19, 38),
('I risultati dell''esperimento X sono stati condivisi con successo con i collaboratori.', DATEADD(day, -2, GETDATE()), 19, 57),
('Complimenti a tutti per l''eccellente lavoro svolto nella fase di sperimentazione!', DATEADD(day, -3, GETDATE()), 19, 19),
('Le nuove metodologie adottate hanno portato a importanti scoperte nella fase di sperimentazione.', DATEADD(day, -1, GETDATE()), 19, 38),
('Grazie a te e a tutto il team per l''impegno costante nella fase di sperimentazione.', GETDATE(), 19, 57);






--SELECT Scientists.Id as ScientistId, Phases.Id  as PhaseId
--FROM ConcordiaStation.dbo.Scientists
--JOIN ConcordiaStation.dbo.Phases ON Scientists.PhaseId = Phases.Id
