using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ConcordiaStation.Data.Migrations
{
    /// <inheritdoc />
    public partial class Add_Dat : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                INSERT INTO ConcordiaStation.dbo.Experiments (Title)
                VALUES
                    ('Esperimento di Fusione Nucleare'),
                    ('Esperimento di Clonazione Genetica'),
                    ('Esperimento di Teletrasporto Molecolare'),
                    ('Esperimento di Bioingegneria'),
                    ('Esperimento di Criogenia'),
                    ('Esperimento di Realtà Virtuale');
            ");

            migrationBuilder.Sql(@"
                            INSERT INTO ConcordiaStation.dbo.Phases (IdCardTrello, Title, DateOfCreation, LastActivity, Deadline, Description, Priority, Status, ExperimentId)
                            VALUES
                    ('card_trello', 'Calibrazione strumenti', '2023-06-10', '2023-06-10', '2023-06-10', 'La calibrazione degli strumenti è un''attività fondamentale per assicurare la precisione e l''affidabilità delle misurazioni. Durante questa fase, verranno eseguiti test e tarature per garantire che gli strumenti siano correttamente allineati e forniscano risultati accurati. Saranno utilizzati standard di riferimento e procedure specifiche per assicurare una calibrazione completa e documentata.', 1, 1, 1),
                    ('card_trello', 'Preparazione attrezzatura', '2023-06-11', '2023-06-11', '2023-06-11', 'La fase di preparazione dell''attrezzatura è cruciale per garantire che tutti gli strumenti e gli strumenti ausiliari siano pronti e adeguatamente configurati per l''esperimento. Saranno verificate le condizioni operative degli strumenti, effettuate calibrazioni preliminari e organizzati i materiali necessari. L''obiettivo è assicurarsi che l''attrezzatura sia pronta per l''uso e in grado di fornire risultati affidabili.', 2, 1, 1),
                    ('card_trello', 'Prelievo campioni aria', '2023-06-12', '2023-06-12', '2023-06-14', 'Durante questa fase, saranno effettuati prelievi di campioni di aria in diversi punti strategici. I campioni saranno raccolti utilizzando strumenti specifici e seguendo protocolli accurati. L''obiettivo è raccogliere campioni rappresentativi per l''analisi successiva. Saranno prese precauzioni per evitare contaminazioni e garantire l''integrità dei campioni.', 2, 1, 1),
                    ('card_trello', 'Analisi composizione campioni', '2023-06-13', '2023-06-13', '2023-06-13', 'In questa fase, i campioni raccolti saranno sottoposti a analisi approfondite per determinarne la composizione chimica e le proprietà. Verranno utilizzate tecniche analitiche avanzate per identificare e quantificare gli inquinanti presenti nei campioni. I risultati saranno registrati e utilizzati per valutare la qualità dell''aria e fornire informazioni importanti per la ricerca.', 1, 1, 3),
                    ('card_trello', 'Valutazione inquinanti', '2023-06-14', '2023-06-14', '2023-06-14', 'Durante questa fase, verranno valutati i risultati delle analisi degli inquinanti. I dati ottenuti verranno confrontati con i limiti di sicurezza e gli standard di riferimento per determinare il livello di inquinamento dell''aria. Saranno eseguite analisi qualitative e quantitative per valutare l''impatto degli inquinanti sulla salute umana e sull''ambiente circostante.', 2, 0, 1),
                    ('card_trello', 'Preparazione attrezzatura', '2023-06-11', '2023-06-11', '2023-06-11', 'Durante la fase di preparazione dell''attrezzatura, verranno eseguite le seguenti attività: pulizia, controllo dello stato di funzionamento e verifica dei requisiti di sicurezza degli strumenti. Saranno preparati tutti gli strumenti necessari per l''esperimento, assicurandosi che siano adeguatamente configurati e pronti per l''uso.', 2, 1, 2),
                    ('card_trello', 'Prelievo campioni aria', '2023-06-12', '2023-06-12', '2023-06-14', 'Durante la fase di prelievo dei campioni di aria, verranno effettuati prelievi in diversi punti della stazione. Saranno utilizzati strumenti specifici per raccogliere campioni rappresentativi. I campioni saranno successivamente analizzati per valutare la qualità dell''aria e la presenza di eventuali inquinanti.', 2, 1, 2),
                    ('card_trello', 'Analisi composizione campioni', '2023-06-13', '2023-06-13', '2023-06-13', 'Durante la fase di analisi della composizione dei campioni, saranno utilizzate tecniche di laboratorio per determinare la presenza e la quantità di elementi e sostanze chimiche nei campioni raccolti. Sarà eseguita un''analisi chimica dettagliata per comprendere la composizione degli inquinanti e valutarne l''impatto sulla qualità dell''aria.', 3, 1, 2),
                    ('card_trello', 'Valutazione inquinanti', '2023-06-14', '2023-06-14', '2023-06-14', 'La fase di valutazione degli inquinanti prevede l''analisi dei dati ottenuti dall''analisi dei campioni di aria. I risultati saranno confrontati con i limiti di sicurezza e gli standard ambientali per determinare il livello di inquinamento. Sarà valutato l''effetto degli inquinanti sulla salute umana e sull''ambiente circostante.', 2, 0, 2),
                    ('card_trello', 'Preparazione substrato', '2023-06-12', '2023-06-12', '2023-06-12', 'Durante la fase di preparazione del substrato, saranno eseguite le seguenti attività: selezione e preparazione del materiale del substrato, trattamento per garantire la sterilizzazione e l''adeguata idratazione. Il substrato preparato sarà pronto per la successiva coltivazione delle cellule.', 1, 1, 2),
                    ('card_trello', 'Coltivazione cellule', '2023-06-13', '2023-06-13', '2023-06-13', 'Durante la fase di coltivazione delle cellule, verranno seminate le cellule sul substrato preparato. Saranno create le condizioni di coltura ottimali, compresi i parametri di temperatura, umidità e alimentazione. Sarà monitorata la crescita delle cellule nel corso del tempo.', 4, 1, 2),
                    ('card_trello', 'Preparazione reagenti', '2023-06-12', '2023-06-12', '2023-06-14', 'Durante la fase di preparazione dei reagenti, saranno eseguite le seguenti attività: selezione dei reagenti necessari per l''esperimento, preparazione delle soluzioni di lavoro e controllo della loro qualità. I reagenti saranno pronti per essere utilizzati nell''esperimento successivo.', 1, 1, 3),
                    ('card_trello', 'Esecuzione esperimento', '2023-06-13', '2023-06-13', '2023-06-13', 'Durante la fase di esecuzione dell''esperimento, saranno seguiti i protocolli sperimentali stabiliti. I reagenti preparati saranno utilizzati per condurre l''esperimento, eseguendo le operazioni specifiche richieste. Saranno registrati accuratamente i dati e gli eventuali risultati osservati.', 2, 1, 3),
                    ('card_trello', 'Analisi dati', '2023-06-14', '2023-06-14', '2023-06-14', 'Durante la fase di analisi dei dati, saranno elaborati i risultati dell''esperimento e saranno applicati i metodi statistici e le tecniche di analisi appropriati. Verranno generati grafici e tabelle per visualizzare e interpretare i dati raccolti. Saranno tratti conclusioni sulla base delle analisi effettuate.', 1, 0, 1),
                    ('card_trello', 'Preparazione campioni', '2023-06-11', '2023-06-11', '2023-06-11', 'Durante la fase di preparazione dei campioni, saranno eseguite le seguenti attività: raccolta dei campioni di interesse, etichettatura e registrazione dei campioni, preparazione dei campioni per l''analisi successiva. Saranno seguiti protocolli e procedure specifiche per garantire la corretta preparazione dei campioni.', 1, 1, 4),
                    ('card_trello', 'Trattamento campioni', '2023-06-12', '2023-06-12', '2023-06-12', 'Durante la fase di trattamento dei campioni, saranno eseguite le seguenti operazioni: estrazione, separazione, purificazione o altre procedure specifiche per ottenere i componenti di interesse dai campioni. Saranno utilizzati reagenti e apparecchiature appropriate per eseguire il trattamento dei campioni in modo accurato e riproducibile.', 2, 2, 4),
                    ('card_trello', 'Analisi risultati', '2023-06-13', '2023-06-13', '2023-06-13', 'Durante la fase di analisi dei risultati, saranno valutati i dati ottenuti dalle analisi effettuate sui campioni trattati. Saranno applicati metodi e tecniche specifiche per interpretare i risultati e ottenere informazioni significative. Saranno generati rapporti o documenti che riassumono i risultati e le conclusioni dell''analisi.', 0, 1, 4),
                    ('card_trello', 'Preparazione campione', '2023-06-12', '2023-06-12', '2023-06-14', 'Durante la fase di preparazione del campione, saranno eseguite le seguenti attività: raccolta del campione di interesse, manipolazione e trattamento del campione per ottenere una forma o una condizione specifica richiesta per l''esperimento successivo. Saranno seguiti protocolli e procedure specifiche per garantire la corretta preparazione del campione.', 1, 1, 5),
                    ('card_trello', 'Crioconservazione', '2023-06-13', '2023-06-13', '2023-06-13', 'Durante la fase di crioconservazione, il campione sarà sottoposto a un processo di congelamento e conservazione a temperature estremamente basse per preservare le sue caratteristiche. Saranno utilizzati metodi e protocolli specifici per garantire una conservazione a lungo termine del campione in condizioni di bassa temperatura.', 3, 1, 5),
                    ('card_trello', 'Controllo qualità', '2023-06-14', '2023-06-14', '2023-06-14', 'Durante la fase di controllo qualità, saranno eseguite attività per valutare la qualità e l''integrità del campione o dei dati ottenuti dall''esperimento. Saranno utilizzati criteri e parametri specifici per determinare se il campione o i risultati soddisfano gli standard di qualità richiesti. Saranno adottate misure correttive, se necessario, per garantire l''affidabilità dei dati.', 1, 1, 5),
                    ('card_trello', 'Configurazione ambiente virtuale', '2023-06-13', '2023-06-13', '2023-06-13', 'Durante la fase di configurazione dell''ambiente virtuale, saranno impostati i parametri e le condizioni necessari per eseguire l''esperimento o l''analisi in un ambiente virtuale. Saranno create le risorse virtuali e configurati gli strumenti e i software appropriati per svolgere l''attività desiderata. Saranno considerate le esigenze specifiche dell''esperimento o dell''analisi durante la configurazione.', 1, 0, 6),
                    ('card_trello', 'Esecuzione esperimento', '2023-06-14', '2023-06-14', '2023-06-14', 'Durante la fase di esecuzione dell''sperimento, saranno seguite le procedure e i protocolli definiti per ottenere i risultati desiderati. Saranno utilizzati strumenti, attrezzature e reagenti specifici, e saranno eseguite misurazioni, manipolazioni e registrazioni necessarie per l''esperimento.', 3, 1, 6),
                    ('card_trello', 'Valutazione risultati', '2023-06-15', '2023-06-15', '2023-06-15', 'Durante la fase di valutazione dei risultati, saranno analizzati e interpretati i dati e le informazioni ottenute dall''esperimento. Saranno utilizzati metodi, modelli e strumenti appropriati per valutare la validità, la precisione e l''affidabilità dei risultati. Saranno tratti eventuali conclusioni o decisioni in base alle analisi effettuate.',  1, 2, 6);
            ");

            migrationBuilder.Sql(@"
                            INSERT INTO ConcordiaStation.dbo.Scientists (GivenName, FamilyName, PhaseId)
                            VALUES
                            ('John', 'Doe', 1),
                            ('Jane', 'Smith', 2),
                            ('Robert', 'Johnson', 3),
                            ('Michael', 'Brown', 4),
                            ('Emily', 'Davis', 5),
                            ('Daniel', 'Wilson', 6),
                            ('Sophia', 'Taylor', 7),
                            ('David', 'Anderson', 8),
                            ('Olivia', 'Miller', 9),
                            ('William', 'Clark', 10),
                            ('Emma', 'Walker', 11),
                            ('James', 'Harris', 12),
                            ('Ava', 'Lewis', 13),
                            ('Benjamin', 'Hall', 14),
                            ('Mia', 'Robinson', 15),
                            ('Alexander', 'Young', 16),
                            ('Charlotte', 'Lee', 17),
                            ('Daniel', 'Allen', 18),
                            ('Grace', 'Wright', 19),
                            ('Samuel', 'Martin', 1),
                            ('Ella', 'Hall', 2),
                            ('Joseph', 'Baker', 3),
                            ('Scarlett', 'Garcia', 4),
                            ('Matthew', 'Perez', 5),
                            ('Victoria', 'Smith', 6),
                            ('Henry', 'Jackson', 7),
                            ('Lily', 'Davis', 8),
                            ('Anthony', 'White', 9),
                            ('Abigail', 'Thomas', 10),
                            ('Christopher', 'Anderson', 11),
                            ('Sofia', 'Williams', 12),
                            ('Andrew', 'Taylor', 13),
                            ('Grace', 'Martin', 14),
                            ('Jacob', 'Lee', 15),
                            ('Sophia', 'Gonzalez', 16),
                            ('Logan', 'Rodriguez', 17),
                            ('Isabella', 'Walker', 18),
                            ('Ethan', 'Moore', 19),
                            ('Mia', 'Gonzalez', 1),
                            ('Matthew', 'Garcia', 2),
                            ('Olivia', 'Thomas', 3),
                            ('Jayden', 'Anderson', 4),
                            ('Amelia', 'Clark', 5),
                            ('Lucas', 'Young', 6),
                            ('Elizabeth', 'Davis', 7),
                            ('Michael', 'Williams', 8),
                            ('Evelyn', 'Brown', 9),
                            ('Daniel', 'Wilson', 10),
                            ('Madison', 'Smith', 11),
                            ('Aiden', 'Johnson', 12),
                            ('Emily', 'Robinson', 13),
                            ('Jacob', 'Wilson', 14),
                            ('Sophia', 'Hall', 15),
                            ('Alexander', 'White', 16),
                            ('Abigail', 'Jackson', 17),
                            ('Benjamin', 'Brown', 18),
                            ('Ava', 'Miller', 19),
                            ('Matthew', 'Davis', 1),
                            ('Charlotte', 'Moore', 2),
                            ('Samuel', 'Lewis', 3),
                            ('Scarlett', 'Thomas', 4),
                            ('David', 'Taylor', 5),
                            ('Grace', 'Wilson', 6),
                            ('Ethan', 'Anderson', 7),
                            ('Lily', 'Garcia', 8),
                            ('Henry', 'Smith', 9),
                            ('Elizabeth', 'Hall', 10),
                            ('Christopher', 'Martin', 11),
                            ('Sofia', 'Walker', 12),
                            ('Daniel', 'Young', 13),
                            ('Amelia', 'Allen', 14),
                            ('James', 'Jones', 15),
                            ('Avery', 'Clark', 16),
                            ('Emily', 'Rod', 17);
            ");

            migrationBuilder.Sql(@"
                            INSERT INTO ConcordiaStation.dbo.Credentials (Email, Password, ScientistId)
                            VALUES
                            ('admin@admin.it', '$2a$11$AE2w8..IimAm6vlVkfXo3uisXEy.DyDiVfU29.u4jQXGjW/yYfNSO', 1);
            ");

            migrationBuilder.Sql(@"
                            INSERT INTO ConcordiaStation.dbo.Comments (Content, PublicationDate, IdPhaseTrello, IdCommentTrello, PhaseId, ScientistId)
                            VALUES
                            ('Ottimo lavoro sul nuovo algoritmo di analisi dati!', DATEADD(day, -3, GETDATE()), 'id_phase', 'id_comment', 1, 1),
                            ('Stiamo facendo progressi significativi nella sintesi del composto X!', DATEADD(day, -2, GETDATE()), 'id_phase', 'id_comment', 1, 20),
                            ('I risultati preliminari dell''esperimento Y sono molto promettenti.', DATEADD(day, -1, GETDATE()), 'id_phase', 'id_comment', 1, 39),
                            ('Continuate così, il vostro contributo è fondamentale per il progetto.', GETDATE(), 'id_phase', 'id_comment', 1, 58),
                            ('Abbiamo riscontrato alcune sfide nella fase di test del prototipo.', DATEADD(day, -4, GETDATE()), 'id_phase', 'id_comment', 1, 1),
                            ('I dati raccolti oggi forniscono nuove intuizioni sul fenomeno Z.', DATEADD(day, -3, GETDATE()), 'id_phase', 'id_comment', 1, 20),
                            ('Il team ha dimostrato grande collaborazione nel superare gli ostacoli tecnici.', DATEADD(day, -1, GETDATE()), 'id_phase', 'id_comment', 1, 39),
                            ('Oggi abbiamo raggiunto un nuovo record di efficienza!', GETDATE(), 'id_phase', 'id_comment', 1, 58),
                            ('I risultati dell''esperimento W sono stati pubblicati su una rivista di prestigio.', DATEADD(day, -2, GETDATE()), 'id_phase', 'id_comment', 1, 1),
                            ('Complimenti a tutti per l''ottimo lavoro di squadra!', DATEADD(day, -3, GETDATE()), 'id_phase', 'id_comment', 1, 20),
                            ('Le nuove attrezzature acquisite hanno migliorato notevolmente la nostra capacità di ricerca.', DATEADD(day, -1, GETDATE()), 'id_phase', 'id_comment', 1, 39),
                            ('Grazie a tutti per il vostro impegno costante nello studio del fenomeno Y.', GETDATE(), 'id_phase', 'id_comment', 1, 58),
                            ('Grande lavoro nell''analisi dei dati del progetto!', DATEADD(day, -3, GETDATE()), 'id_phase', 'id_comment', 2, 2),
                            ('Stiamo facendo notevoli progressi nello sviluppo del composto Y!', DATEADD(day, -2, GETDATE()), 'id_phase', 'id_comment', 2, 21),
                            ('I risultati dell''esperimento Z sono molto promettenti.', DATEADD(day, -1, GETDATE()), 'id_phase', 'id_comment', 2, 40),
                            ('Il tuo contributo è essenziale per il successo del progetto. Continua così!', GETDATE(), 'id_phase', 'id_comment', 2, 59),
                            ('Abbiamo incontrato alcune sfide durante i test del prototipo. Rimani concentrato!', DATEADD(day, -4, GETDATE()), 'id_phase', 'id_comment', 2, 2),
                            ('I dati raccolti oggi forniscono nuove prospettive sul fenomeno X.', DATEADD(day, -3, GETDATE()), 'id_phase', 'id_comment', 2, 21),
                            ('Il team ha dimostrato grande collaborazione nel superare gli ostacoli tecnici.', DATEADD(day, -1, GETDATE()), 'id_phase', 'id_comment', 2, 40),
                            ('Oggi abbiamo raggiunto un nuovo record di efficienza nel laboratorio!', GETDATE(), 'id_phase', 'id_comment', 2, 59),
                            ('Ottimo lavoro nella fase di sviluppo avanzato!', DATEADD(day, -3, GETDATE()), 'id_phase', 'id_comment', 3, 3),
                            ('Continuiamo a fare progressi significativi nella ricerca del composto Z!', DATEADD(day, -2, GETDATE()), 'id_phase', 'id_comment', 3, 22),
                            ('I risultati dell''esperimento X sono molto interessanti.', DATEADD(day, -1, GETDATE()), 'id_phase', 'id_comment', 3, 41),
                            ('Il tuo contributo è fondamentale per il successo della fase sperimentale. Grazie!', GETDATE(), 'id_phase', 'id_comment', 3, 60),
                            ('Abbiamo superato con successo le sfide nella fase di test del nuovo dispositivo.', DATEADD(day, -4, GETDATE()), 'id_phase', 'id_comment', 3, 3),
                            ('I dati raccolti oggi forniscono nuove intuizioni sul fenomeno Y.', DATEADD(day, -3, GETDATE()), 'id_phase', 'id_comment', 3, 22),
                            ('Il team ha dimostrato una grande collaborazione nel raggiungimento degli obiettivi.', DATEADD(day, -1, GETDATE()), 'id_phase', 'id_comment', 3, 41),
                            ('Oggi abbiamo raggiunto un importante traguardo nella ricerca!', GETDATE(), 'id_phase', 'id_comment', 3, 60),
                            ('I risultati dell''esperimento W sono stati presentati con successo alla conferenza internazionale.', DATEADD(day, -2, GETDATE()), 'id_phase', 'id_comment', 3, 3),
                            ('Complimenti a tutti per l''eccellente lavoro svolto!', DATEADD(day, -3, GETDATE()), 'id_phase', 'id_comment', 3, 22),
                            ('Le nuove attrezzature acquisite hanno migliorato notevolmente la nostra produttività di laboratorio.', DATEADD(day, -1, GETDATE()), 'id_phase', 'id_comment', 3, 41),
                            ('Grazie a te e a tutto il team per l''impegno costante nella fase di ricerca avanzata.', DATEADD(day, -1, GETDATE()), 'id_phase', 'id_comment', 3, 60),
                            ('Il progetto nella fase di valutazione è in buon andamento!', DATEADD(day, -3, GETDATE()), 'id_phase', 'id_comment', 4, 4),
                            ('Stiamo ottenendo risultati promettenti nello studio del composto A!', DATEADD(day, -2, GETDATE()), 'id_phase', 'id_comment', 4, 23),
                            ('I dati preliminari dell''esperimento B sono molto interessanti.', DATEADD(day, -1, GETDATE()), 'id_phase', 'id_comment', 4, 42),
                            ('Il tuo contributo è fondamentale per il successo della fase di valutazione. Grazie per l''impegno!', GETDATE(), 'id_phase', 'id_comment', 4, 61),
                            ('Abbiamo superato con successo le sfide nella fase di test del nuovo prototipo.', DATEADD(day, -4, GETDATE()), 'id_phase', 'id_comment', 4, 4),
                            ('I dati raccolti oggi forniscono ulteriori intuizioni sul fenomeno C.', DATEADD(day, -3, GETDATE()), 'id_phase', 'id_comment', 4, 23),
                            ('Il team ha dimostrato una grande collaborazione nel raggiungimento degli obiettivi.', DATEADD(day, -1, GETDATE()), 'id_phase', 'id_comment', 4, 42),
                            ('Oggi abbiamo raggiunto un importante traguardo nella fase di valutazione!', GETDATE(), 'id_phase', 'id_comment', 4, 61),
                            ('I risultati dell''esperimento D sono stati condivisi con successo con i colleghi.', DATEADD(day, -2, GETDATE()), 'id_phase', 'id_comment', 4, 4),
                            ('Complimenti a tutti per l''eccellente lavoro svolto nella fase di valutazione!', DATEADD(day, -3, GETDATE()), 'id_phase', 'id_comment', 4, 23),
                            ('Le nuove attrezzature acquisite hanno migliorato notevolmente la nostra produttività di laboratorio.', DATEADD(day, -1, GETDATE()), 'id_phase', 'id_comment', 4, 42),
                            ('Grazie a te e a tutto il team per l''impegno costante nella fase di valutazione del progetto.', GETDATE(), 'id_phase', 'id_comment', 4, 61),
                            ('Stiamo facendo grandi progressi nella fase di ottimizzazione!', DATEADD(day, -3, GETDATE()), 'id_phase', 'id_comment', 5, 5),
                            ('Continuiamo a ottenere risultati significativi nello studio del composto D!', DATEADD(day, -2, GETDATE()), 'id_phase', 'id_comment', 5, 23),
                            ('I dati preliminari dell''esperimento E sono molto promettenti.', DATEADD(day, -1, GETDATE()), 'id_phase', 'id_comment', 5, 43),
                            ('Il tuo contributo è fondamentale per il successo della fase di ottimizzazione. Grazie per il tuo impegno!', GETDATE(), 'id_phase', 'id_comment', 5, 62),
                            ('Abbiamo superato con successo le sfide nella fase di test del nuovo processo.', DATEADD(day, -4, GETDATE()), 'id_phase', 'id_comment', 5, 5),
                            ('I dati raccolti oggi forniscono nuove prospettive sul fenomeno F.', DATEADD(day, -3, GETDATE()), 'id_phase', 'id_comment', 5, 24),
                            ('Il team ha dimostrato grande collaborazione nel raggiungimento degli obiettivi.', DATEADD(day, -1, GETDATE()), 'id_phase', 'id_comment', 5, 43),
                            ('I risultati dell''esperimento W sono stati pubblicati su una rinomata rivista scientifica.', DATEADD(day, -2, GETDATE()), 'id_phase', 'id_comment', 2, 2),
                            ('Complimenti a tutti per il fantastico lavoro svolto insieme!', DATEADD(day, -3, GETDATE()), 'id_phase', 'id_comment', 2, 21),
                            ('Le nuove attrezzature acquisite hanno potenziato le nostre capacità di ricerca.', DATEADD(day, -1, GETDATE()), 'id_phase', 'id_comment', 2, 40),
                            ('Grazie a te e a tutto il team per l''impegno costante nella ricerca di nuove soluzioni.', GETDATE(), 'id_phase', 'id_comment', 2, 59),
                            ('Oggi abbiamo raggiunto un importante traguardo nella fase di ottimizzazione!', GETDATE(), 'id_phase', 'id_comment', 5, 62),
                            ('I risultati dell''esperimento G sono stati condivisi con successo con i partner.', DATEADD(day, -2, GETDATE()), 'id_phase', 'id_comment', 5, 5),
                            ('Complimenti a tutti per l''eccellente lavoro svolto nella fase di ottimizzazione!', DATEADD(day, -3, GETDATE()), 'id_phase', 'id_comment', 5, 24),
                            ('Le nuove attrezzature acquisite hanno migliorato notevolmente la nostra produttività di laboratorio.', DATEADD(day, -1, GETDATE()), 'id_phase', 'id_comment', 5, 43),
                            ('Grazie a te e a tutto il team per l''impegno costante nella fase di ottimizzazione del progetto.', GETDATE(), 'id_phase', 'id_comment', 5, 62),
                            ('Il progetto nella fase di ottimizzazione avanzata sta procedendo alla grande!', DATEADD(day, -3, GETDATE()), 'id_phase', 'id_comment', 6, 6),
                            ('Stiamo ottenendo risultati eccezionali nello studio del composto G!', DATEADD(day, -2, GETDATE()), 'id_phase', 'id_comment', 6, 25),
                            ('I dati preliminari dell''esperimento H sono molto promettenti.', DATEADD(day, -1, GETDATE()), 'id_phase', 'id_comment', 6, 44),
                            ('Il tuo contributo è fondamentale per il successo della fase di ottimizzazione avanzata. Grazie per l''impegno!', GETDATE(), 'id_phase', 'id_comment', 6, 63),
                            ('Abbiamo superato con successo le sfide nella fase di test del nuovo approccio.', DATEADD(day, -4, GETDATE()), 'id_phase', 'id_comment', 6, 6),
                            ('I dati raccolti oggi forniscono nuove prospettive sul fenomeno I.', DATEADD(day, -3, GETDATE()), 'id_phase', 'id_comment', 6, 25),
                            ('Il team ha dimostrato una grande collaborazione nel raggiungimento degli obiettivi.', DATEADD(day, -1, GETDATE()), 'id_phase', 'id_comment', 6, 44),
                            ('Oggi abbiamo raggiunto un importante traguardo nella fase di ottimizzazione avanzata!', GETDATE(), 'id_phase', 'id_comment', 6, 63),
                            ('I risultati dell''esperimento J sono stati condivisi con successo con i collaboratori.', DATEADD(day, -2, GETDATE()), 'id_phase', 'id_comment', 6, 6),
                            ('Complimenti a tutti per l''eccellente lavoro svolto nella fase di ottimizzazione avanzata!', DATEADD(day, -3, GETDATE()), 'id_phase', 'id_comment', 6, 25),
                            ('Le nuove attrezzature acquisite hanno migliorato notevolmente la nostra produttività di laboratorio.', DATEADD(day, -1, GETDATE()), 'id_phase', 'id_comment', 6, 44),
                            ('Grazie a te e a tutto il team per l''impegno costante nella fase di ottimizzazione avanzata del progetto.', GETDATE(), 'id_phase', 'id_comment', 6, 63),
                            ('Il progetto nella fase finale sta raggiungendo risultati straordinari!', DATEADD(day, -3, GETDATE()), 'id_phase', 'id_comment', 7, 7),
                            ('Stiamo facendo progressi significativi nello studio del composto J!', DATEADD(day, -2, GETDATE()), 'id_phase', 'id_comment', 7, 26),
                            ('I risultati preliminari dell''esperimento K sono molto promettenti.', DATEADD(day, -1, GETDATE()), 'id_phase', 'id_comment', 7, 45),
                            ('Il tuo contributo è fondamentale per il successo della fase finale. Grazie per l''impegno!', GETDATE(), 'id_phase', 'id_comment', 7, 64),
                            ('Abbiamo superato con successo le sfide nella fase di test del nuovo sistema.', DATEADD(day, -4, GETDATE()), 'id_phase', 'id_comment', 7, 7),
                            ('I dati raccolti oggi forniscono ulteriori intuizioni sul fenomeno L.', DATEADD(day, -3, GETDATE()), 'id_phase', 'id_comment', 7, 26),
                            ('Il team ha dimostrato una grande collaborazione nel raggiungimento degli obiettivi.', DATEADD(day, -1, GETDATE()), 'id_phase', 'id_comment', 7, 45),
                            ('Oggi abbiamo raggiunto un importante traguardo nella fase finale!', GETDATE(), 'id_phase', 'id_comment', 7, 64),
                            ('I risultati dell''esperimento M sono stati condivisi con successo con i partner di ricerca.', DATEADD(day, -2, GETDATE()), 'id_phase', 'id_comment', 7, 7),
                            ('Complimenti a tutti per l''eccellente lavoro svolto nella fase finale del progetto!', DATEADD(day, -3, GETDATE()), 'id_phase', 'id_comment', 7, 26),
                            ('Le nuove attrezzature acquisite hanno migliorato notevolmente la nostra produttività di laboratorio.', DATEADD(day, -1, GETDATE()), 'id_phase', 'id_comment', 7, 45),
                            ('Grazie a te e a tutto il team per l''impegno costante nella fase finale del progetto.', GETDATE(), 'id_phase', 'id_comment', 7, 64),
                            ('I risultati ottenuti nella fase finale superano ogni aspettativa!', DATEADD(day, -3, GETDATE()), 'id_phase', 'id_comment', 8, 8),
                            ('Stiamo compiendo grandi progressi nello studio del composto M!', DATEADD(day, -2, GETDATE()), 'id_phase', 'id_comment', 8, 27),
                            ('I risultati preliminari dell''esperimento N sono estremamente promettenti.', DATEADD(day, -1, GETDATE()), 'id_phase', 'id_comment', 8, 46),
                            ('Il tuo contributo è fondamentale per il successo della fase finale. Grazie per l''impegno!', GETDATE(), 'id_phase', 'id_comment', 8, 65),
                            ('Abbiamo superato con successo le sfide nella fase di test del nuovo dispositivo.', DATEADD(day, -4, GETDATE()), 'id_phase', 'id_comment', 8, 8),
                            ('I dati raccolti oggi offrono nuove prospettive sul fenomeno O.', DATEADD(day, -3, GETDATE()), 'id_phase', 'id_comment', 8, 27),
                            ('Il team ha dimostrato una straordinaria collaborazione nel raggiungimento degli obiettivi.', DATEADD(day, -1, GETDATE()), 'id_phase', 'id_comment', 8, 46),
                            ('Oggi abbiamo raggiunto un traguardo eccezionale nella fase finale!', GETDATE(), 'id_phase', 'id_comment', 8, 65),
                            ('I risultati dell''esperimento P sono stati condivisi con successo con i collaboratori.', DATEADD(day, -2, GETDATE()), 'id_phase', 'id_comment', 8, 8),
                            ('Complimenti a tutti per l''eccellente lavoro svolto nella fase finale del progetto!', DATEADD(day, -3, GETDATE()), 'id_phase', 'id_comment', 8, 27),
                            ('Le nuove attrezzature acquisite hanno notevolmente migliorato la nostra produttività di laboratorio.', DATEADD(day, -1, GETDATE()), 'id_phase', 'id_comment', 8, 46),
                            ('Grazie a te e a tutto il team per l''impegno costante nella fase finale del progetto.', GETDATE(), 'id_phase', 'id_comment', 8, 65),
                            ('I risultati ottenuti nella fase avanzata sono eccezionali!', DATEADD(day, -3, GETDATE()), 'id_phase', 'id_comment', 9, 9),
                            ('Stiamo facendo notevoli progressi nello studio del composto P!', DATEADD(day, -2, GETDATE()), 'id_phase', 'id_comment', 9, 28),
                            ('I risultati preliminari dell''esperimento Q sono molto promettenti.', DATEADD(day, -1, GETDATE()), 'id_phase', 'id_comment', 9, 47),
                            ('Il tuo contributo è fondamentale per il successo della fase avanzata. Grazie per l''impegno!', GETDATE(), 'id_phase', 'id_comment', 9, 66),
                            ('Abbiamo superato con successo le sfide nella fase di test del nuovo metodo di analisi.', DATEADD(day, -4, GETDATE()), 'id_phase', 'id_comment', 9, 9),
                            ('I dati raccolti oggi forniscono ulteriori intuizioni sul fenomeno R.', DATEADD(day, -3, GETDATE()), 'id_phase', 'id_comment', 9, 28),
                            ('Il team ha dimostrato una grande sinergia nel raggiungimento degli obiettivi.', DATEADD(day, -1, GETDATE()), 'id_phase', 'id_comment', 9, 47),
                            ('Oggi abbiamo raggiunto un importante traguardo nella fase avanzata!', GETDATE(), 'id_phase', 'id_comment', 9, 66),
                            ('I risultati dell''esperimento S sono stati condivisi con successo con i collaboratori.', DATEADD(day, -2, GETDATE()), 'id_phase', 'id_comment', 9, 9),
                            ('Complimenti a tutti per l''eccellente lavoro svolto nella fase avanzata del progetto!', DATEADD(day, -3, GETDATE()), 'id_phase', 'id_comment', 9, 28),
                            ('Le nuove attrezzature acquisite hanno migliorato significativamente la nostra capacità di ricerca.', DATEADD(day, -1, GETDATE()), 'id_phase', 'id_comment', 9, 47),
                            ('Grazie a te e a tutto il team per l''impegno costante nella fase avanzata del progetto.', GETDATE(), 'id_phase', 'id_comment', 9, 66),
                            ('I risultati ottenuti nella fase avanzata sono sorprendenti!', DATEADD(day, -3, GETDATE()), 'id_phase', 'id_comment', 10, 10),
                            ('Stiamo facendo progressi significativi nello studio del composto Q!', DATEADD(day, -2, GETDATE()), 'id_phase', 'id_comment', 10, 29),
                            ('I risultati preliminari dell''esperimento R sono estremamente promettenti.', DATEADD(day, -1, GETDATE()), 'id_phase', 'id_comment', 10, 48),
                            ('Il tuo contributo è fondamentale per il successo della fase avanzata. Grazie per l''impegno!', GETDATE(), 'id_phase', 'id_comment', 10, 67),
                            ('Abbiamo superato con successo le sfide nella fase di test del nuovo dispositivo di misurazione.', DATEADD(day, -4, GETDATE()), 'id_phase', 'id_comment', 10, 10),
                            ('I dati raccolti oggi offrono nuove prospettive sul fenomeno S.', DATEADD(day, -3, GETDATE()), 'id_phase', 'id_comment', 10, 29),
                            ('Il team ha dimostrato una straordinaria sinergia nel raggiungimento degli obiettivi.', DATEADD(day, -1, GETDATE()), 'id_phase', 'id_comment', 10, 48),
                            ('Oggi abbiamo raggiunto un traguardo eccezionale nella fase avanzata!', GETDATE(), 'id_phase', 'id_comment', 10, 67),
                            ('I risultati dell''esperimento T sono stati condivisi con successo con i collaboratori.', DATEADD(day, -2, GETDATE()), 'id_phase', 'id_comment', 10, 10),
                            ('Complimenti a tutti per l''eccellente lavoro svolto nella fase avanzata del progetto!', DATEADD(day, -3, GETDATE()), 'id_phase', 'id_comment', 10, 29),
                            ('Le nuove attrezzature acquisite hanno notevolmente migliorato la nostra capacità di ricerca.', DATEADD(day, -1, GETDATE()), 'id_phase', 'id_comment', 10, 48),
                            ('Grazie a te e a tutto il team per l''impegno costante nella fase avanzata del progetto.', GETDATE(), 'id_phase', 'id_comment', 10, 67),
                            ('I risultati ottenuti nella fase finale superano ogni aspettativa!', DATEADD(day, -3, GETDATE()), 'id_phase', 'id_comment', 11, 11),
                            ('Stiamo compiendo grandi progressi nello studio del composto T!', DATEADD(day, -2, GETDATE()), 'id_phase', 'id_comment', 11, 30),
                            ('I risultati preliminari dell''esperimento U sono molto promettenti.', DATEADD(day, -1, GETDATE()), 'id_phase', 'id_comment', 11, 49),
                            ('Il tuo contributo è fondamentale per il successo della fase finale. Grazie per l''impegno!', GETDATE(), 'id_phase', 'id_comment', 11, 68),
                            ('Abbiamo superato con successo le sfide nella fase di test del nuovo metodo di analisi.', DATEADD(day, -4, GETDATE()), 'id_phase', 'id_comment', 11, 11),
                            ('I dati raccolti oggi forniscono nuove intuizioni sul fenomeno V.', DATEADD(day, -3, GETDATE()), 'id_phase', 'id_comment', 11, 30),
                            ('Il team ha dimostrato una grande collaborazione nel raggiungimento degli obiettivi.', DATEADD(day, -1, GETDATE()), 'id_phase', 'id_comment', 11, 49),
                            ('Oggi abbiamo raggiunto un traguardo eccezionale nella fase finale!', GETDATE(), 'id_phase', 'id_comment', 11, 68),
                            ('I risultati dell''esperimento W sono stati condivisi con successo con i collaboratori.', DATEADD(day, -2, GETDATE()), 'id_phase', 'id_comment', 11, 11),
                            ('Complimenti a tutti per l''eccellente lavoro svolto nella fase finale del progetto!', DATEADD(day, -3, GETDATE()), 'id_phase', 'id_comment', 11, 30),
                            ('Le nuove attrezzature acquisite hanno migliorato notevolmente la nostra capacità di ricerca.', DATEADD(day, -1, GETDATE()), 'id_phase', 'id_comment', 11, 49),
                            ('Grazie a te e a tutto il team per l''impegno costante nella fase finale del progetto.', GETDATE(), 'id_phase', 'id_comment', 11, 68),
                            ('I risultati ottenuti nella fase di analisi sono sorprendenti!', DATEADD(day, -3, GETDATE()), 'id_phase', 'id_comment', 12, 12),
                            ('Stiamo facendo progressi significativi nello studio del fenomeno U!', DATEADD(day, -2, GETDATE()), 'id_phase', 'id_comment', 12, 31),
                            ('I risultati preliminari dell''esperimento V sono estremamente promettenti.', DATEADD(day, -1, GETDATE()), 'id_phase', 'id_comment', 12, 50),
                            ('Il tuo contributo è fondamentale per il successo della fase di analisi. Grazie per l''impegno!', GETDATE(), 'id_phase', 'id_comment', 12, 69),
                            ('Abbiamo superato con successo le sfide nella fase di elaborazione dei dati.', DATEADD(day, -4, GETDATE()), 'id_phase', 'id_comment', 12, 12),
                            ('I dati raccolti oggi offrono nuove prospettive sul fenomeno W.', DATEADD(day, -3, GETDATE()), 'id_phase', 'id_comment', 12, 31),
                            ('Il team ha dimostrato una straordinaria sinergia nella fase di analisi.', DATEADD(day, -1, GETDATE()), 'id_phase', 'id_comment', 12, 50),
                            ('Oggi abbiamo raggiunto un traguardo eccezionale nella fase di analisi!', GETDATE(), 'id_phase', 'id_comment', 12, 69),
                            ('I risultati dell''esperimento X sono stati condivisi con successo con i collaboratori.', DATEADD(day, -2, GETDATE()), 'id_phase', 'id_comment', 12, 12),
                            ('Complimenti a tutti per l''eccellente lavoro svolto nella fase di analisi del progetto!', DATEADD(day, -3, GETDATE()), 'id_phase', 'id_comment', 12, 31),
                            ('Grazie a te e a tutto il team per l''impegno costante nella fase di sperimentazione.', GETDATE(), 'id_phase', 'id_comment', 16, 73),
                            ('Siamo entusiasti dei risultati ottenuti nella fase di analisi dei dati!', DATEADD(day, -3, GETDATE()), 'id_phase', 'id_comment', 17, 17),
                            ('Stiamo facendo progressi significativi nella comprensione del fenomeno M!', DATEADD(day, -2, GETDATE()), 'id_phase', 'id_comment', 17, 36),
                            ('I risultati preliminari dell''esperimento N sono molto promettenti.', DATEADD(day, -1, GETDATE()), 'id_phase', 'id_comment', 17, 55),
                            ('Il tuo contributo è fondamentale per il successo della fase di analisi dei dati. Grazie per l''impegno!', GETDATE(), 'id_phase', 'id_comment', 17, 74),
                            ('Abbiamo superato con successo le sfide nella fase di elaborazione dei risultati.', DATEADD(day, -4, GETDATE()), 'id_phase', 'id_comment', 17, 17),
                            ('I dati raccolti oggi ci forniscono nuove prospettive sul fenomeno O.', DATEADD(day, -3, GETDATE()), 'id_phase', 'id_comment', 17, 36),
                            ('Il team ha dimostrato grande collaborazione nel superare gli ostacoli nella fase di analisi dei dati.', DATEADD(day, -1, GETDATE()), 'id_phase', 'id_comment', 17, 55),
                            ('Oggi abbiamo ottenuto risultati eccezionali nella fase di analisi dei dati!', DATEADD(day, -3, GETDATE()), 'id_phase', 'id_comment', 17, 74),
                            ('I risultati dell''esperimento P sono stati condivisi con successo con i collaboratori.', DATEADD(day, -2, GETDATE()), 'id_phase', 'id_comment', 17, 17),
                            ('Complimenti a tutti per l''ottimo lavoro di squadra nella fase di analisi dei dati!', DATEADD(day, -3, GETDATE()), 'id_phase', 'id_comment', 17, 36),
                            ('Le nuove metodologie adottate hanno migliorato notevolmente la nostra capacità di analisi dei dati.', DATEADD(day, -1, GETDATE()), 'id_phase', 'id_comment', 17, 55),
                            ('Grazie a tutti per il vostro impegno costante nella fase di analisi dei dati.', GETDATE(), 'id_phase', 'id_comment', 17, 74),
                            ('I risultati ottenuti nella fase di ottimizzazione sono sorprendenti!', DATEADD(day, -3, GETDATE()), 'id_phase', 'id_comment', 18, 18),
                            ('Stiamo facendo importanti progressi nella ricerca sul fenomeno Q!', DATEADD(day, -2, GETDATE()), 'id_phase', 'id_comment', 18, 37),
                            ('I risultati preliminari dell''esperimento R sono molto promettenti.', DATEADD(day, -1, GETDATE()), 'id_phase', 'id_comment', 18, 56),
                            ('Il tuo contributo è fondamentale per il successo della fase di ottimizzazione. Grazie per l''impegno!', GETDATE(), 'id_phase', 'id_comment', 18, 56),
                            ('Abbiamo superato con successo le sfide nella fase di implementazione delle nuove strategie.', DATEADD(day, -4, GETDATE()), 'id_phase', 'id_comment', 18, 18),
                            ('I dati raccolti oggi ci offrono nuove prospettive sul fenomeno S.', DATEADD(day, -3, GETDATE()), 'id_phase', 'id_comment', 18, 37),
                            ('Il team ha dimostrato una grande collaborazione nel superare gli ostacoli nella fase di ottimizzazione.', DATEADD(day, -1, GETDATE()), 'id_phase', 'id_comment', 18, 56),
                            ('Oggi abbiamo raggiunto un risultato eccezionale nella fase di ottimizzazione!', DATEADD(day, -3, GETDATE()), 'id_phase', 'id_comment', 18, 56),
                            ('I risultati dell''esperimento T sono stati condivisi con successo con i collaboratori.', DATEADD(day, -2, GETDATE()), 'id_phase', 'id_comment', 18, 18),
                            ('Complimenti a tutti per l''eccellente lavoro svolto nella fase di ottimizzazione!', DATEADD(day, -3, GETDATE()), 'id_phase', 'id_comment', 18, 37),
                            ('Le nuove metodologie adottate hanno portato a significativi miglioramenti nella fase di ottimizzazione.', DATEADD(day, -1, GETDATE()), 'id_phase', 'id_comment', 18, 56),
                            ('Grazie a te e a tutto il team per l''impegno costante nella fase di ottimizzazione.', GETDATE(), 'id_phase', 'id_comment', 18, 37),
                            ('Abbiamo raggiunto un importante traguardo nella fase di sperimentazione.', DATEADD(day, -3, GETDATE()), 'id_phase', 'id_comment', 19, 19),
                            ('Stiamo facendo notevoli progressi nello studio del fenomeno U!', DATEADD(day, -2, GETDATE()), 'id_phase', 'id_comment', 19, 38),
                            ('I risultati preliminari dell''esperimento V sono molto promettenti.', DATEADD(day, -1, GETDATE()), 'id_phase', 'id_comment', 19, 57),
                            ('Il tuo contributo è fondamentale per il successo della fase di sperimentazione. Grazie per l''impegno!', GETDATE(), 'id_phase', 'id_comment', 19, 19),
                            ('Abbiamo superato con successo le sfide nella fase di validazione dei dati.', DATEADD(day, -4, GETDATE()), 'id_phase', 'id_comment', 19, 38),
                            ('I dati raccolti oggi ci offrono nuove prospettive sul fenomeno W.', DATEADD(day, -3, GETDATE()), 'id_phase', 'id_comment', 19, 57),
                            ('Il team ha dimostrato una grande collaborazione nel superare gli ostacoli nella fase di sperimentazione.', DATEADD(day, -1, GETDATE()), 'id_phase', 'id_comment', 19, 19),
                            ('Oggi abbiamo raggiunto un risultato eccezionale nella fase di sperimentazione!', GETDATE(), 'id_phase', 'id_comment', 19, 38),
                            ('I risultati dell''esperimento X sono stati condivisi con successo con i collaboratori.', DATEADD(day, -2, GETDATE()), 'id_phase', 'id_comment', 19, 57),
                            ('Complimenti a tutti per l''eccellente lavoro svolto nella fase di sperimentazione!', DATEADD(day, -3, GETDATE()), 'id_phase', 'id_comment', 19, 19),
                            ('Le nuove metodologie adottate hanno portato a importanti scoperte nella fase di sperimentazione.', DATEADD(day, -1, GETDATE()), 'id_phase', 'id_comment', 19, 38),
                            ('Grazie a te e a tutto il team per l''impegno costante nella fase di sperimentazione.', GETDATE(), 'id_phase', 'id_comment', 19, 57);
            ");

        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
